### PR TITLE
Darken editor background color to improve contrast

### PR DESCRIPTION
**Pull request by waldyrious**
I love this theme but I've been struggling with contrast in some of the monitors I use.

This change allows more contrast between foreground and background elements in the editor areas, but still keeps the overall tint of the background color, to remain faithful to the theme's spirit.

Edit: I've also changed the line highlight color and the selection background color, to match the general background darkening.

Any feedback / suggestions welcome!

### CODE REVIEW

**Comment by waldyrious** [comment]
Before:

Screenshot 2019-03-24 at 22 18 28

After:

Screenshot 2019-03-24 at 22 18 47

**Comment by waldyrious** [comment]
Note: I plan on testing these changes for a few days, and will update the PR to address any additional issues I encounter.

**Comment by waldyrious** [comment]
Upon further testing, I noticed that the darker shade I proposed (`#202326`) is a little warmer than the other colors used in the theme, so I tweaked it to `#202329`. This fits better with the overall slightly bluish tint of the theme, but it also makes it too close to the sidebar color. Therefore I tried darkening it a bit more, to `#1c2126`. I'll continue with this one for some more days and will report back.

Screenshots for the colors mentioned above (note that these all use the same line highlight color, `#30363c`, so take that into account when comparing these images):

`#282c34` (current color):
Screenshot 2019-03-27 at 17 05 07 (original)

`#202326` (original darker proposal of this PR):
Screenshot 2019-03-27 at 17 04 45 (#202326)

`#202329` (closer to blue tone used elsewhere):
Screenshot 2019-03-27 at 16 59 39 (#202329)

`#1c2126` (darker to distinguish from the sidebar):
Screenshot 2019-03-27 at 17 04 19 (#1c2126)

**Comment by Hezkore** [comment]
I personally prefer the "original" theme a lot more than your contrast adjusted one.
But I do understand the need for such a theme!
So I think that instead of replacing the original theme; your theme should come as a second option.
'OneMonokai-Contrast' or something similar.

**Comment by azemoh** [comment]
@waldyrious I wouldn't want to change the background color for the same reasons @Hezkore mentioned. However, you are welcome to create a "Contrast" variant.  I've added an Issue of that here #35

**Pull request closed without merging**
